name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_BASE_API_URL=${{ vars.NEXT_PUBLIC_BASE_API_URL || 'http://localhost:3000/api' }}
            NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co' }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-key' }}
            NEXT_PUBLIC_DEPLOYMENTS=${{ vars.NEXT_PUBLIC_DEPLOYMENTS || '[{"id":"default","deploymentUrl":"http://localhost:8123","tenantId":"default","name":"Default Agent","isDefault":true,"defaultGraphId":"agent"}]' }}
            NEXT_PUBLIC_GOOGLE_AUTH_DISABLED=${{ vars.NEXT_PUBLIC_GOOGLE_AUTH_DISABLED || 'false' }}
            NEXT_PUBLIC_USE_LANGSMITH_AUTH=${{ vars.NEXT_PUBLIC_USE_LANGSMITH_AUTH || 'false' }}
            NEXT_PUBLIC_RAG_API_URL=${{ vars.NEXT_PUBLIC_RAG_API_URL || '' }}
            NEXT_PUBLIC_MCP_SERVER_URL=${{ vars.NEXT_PUBLIC_MCP_SERVER_URL || '' }}
            NEXT_PUBLIC_MCP_AUTH_REQUIRED=${{ vars.NEXT_PUBLIC_MCP_AUTH_REQUIRED || 'false' }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json